events { worker_connections 1024; }

http {
    # ── upstream pools (para HA si hay 2 VMs idénticas) ────────
    upstream ms1 { server ms1-catalogo:8001; }
    upstream ms2 { server ms2-pedidos:8002;  }
    upstream ms3 { server ms3-resenas:8003;  }

    server {
        listen 80;
        server_name _;

        # Rutas por microservicio
        location /libros      { proxy_pass http://ms1; proxy_set_header Host $host; }
        location /autores     { proxy_pass http://ms1; proxy_set_header Host $host; }
        location /generos     { proxy_pass http://ms1; proxy_set_header Host $host; }
        location /editoriales { proxy_pass http://ms1; proxy_set_header Host $host; }

        location /pedidos     { proxy_pass http://ms2; proxy_set_header Host $host; }
        location /clientes    { proxy_pass http://ms2; proxy_set_header Host $host; }

        location /resenas     { proxy_pass http://ms3; proxy_set_header Host $host; }

        # Health global
        location /health {
            return 200 '{"status":"ok","vm":"vm1"}';
            add_header Content-Type application/json;
        }
    }
}
