events { worker_connections 1024; }

http {
    upstream ms4 { server ms4-agregador:8004;  }
    upstream ms5 { server ms5-analytics:8005;  }

    server {
        listen 80;
        server_name _;

        location /perfil-cliente   { proxy_pass http://ms4; proxy_set_header Host $host; }
        location /detalle-libro    { proxy_pass http://ms4; proxy_set_header Host $host; }
        location /resumen-pedido   { proxy_pass http://ms4; proxy_set_header Host $host; }
        location /catalogo-con-stats { proxy_pass http://ms4; proxy_set_header Host $host; }

        location /ventas-por-genero  { proxy_pass http://ms5; proxy_set_header Host $host; }
        location /top-autores        { proxy_pass http://ms5; proxy_set_header Host $host; }
        location /top-clientes       { proxy_pass http://ms5; proxy_set_header Host $host; }
        location /rating-por-genero  { proxy_pass http://ms5; proxy_set_header Host $host; }
        location /libros-mas-vendidos { proxy_pass http://ms5; proxy_set_header Host $host; }

        location /health {
            return 200 '{"status":"ok","vm":"vm2"}';
            add_header Content-Type application/json;
        }
    }
}
